sudo: required

language: perl

perl:
  - "5.26-shrplib"

dist:
  - bionic

addons:
  apt:
    packages:
    - libgd-dev
    - liblzma-dev
    - uuid-dev

env:
  global:
    - TEST_AUTHOR=1
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg

before_install:
  - ./.travis/install.sh
  - cpanm --quiet --notest --installdeps .

