name: testing_and_building_repo
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04']
        perl: ['5.26']

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l -e -o pipefail {0}

    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: install apt deps
      run: |
          sudo apt-get install -y libgd-dev liblzma-dev uuid-dev

    - name: install cpanm
      run: |
          wget -qO - https://cpanmin.us | /usr/bin/perl - --sudo App::cpanminus

    - name: run install script
      run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib=~/perl5)
          ${GITHUB_WORKSPACE}/scripts/install.sh
      env:
        WTSI_NPG_GITHUB_URL: https://github.com/wtsi-npg
        WTSI_NPG_BUILD_BRANCH: ${GITHUB_HEAD_REF}

    - name: run test
      run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib=~/perl5)
          cpanm --notest --installdeps .
          perl Build.PL && ./Build test --verbose && ./Build install
      env:
        WTSI_NPG_BUILD_BRANCH: ${GITHUB_HEAD_REF}
        TEST_AUTHOR: 1

    # Archive logs if failure
    - name: Archive CPAN logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: cpan_log
        path: /home/runner/.cpanm/work/*/build.log
        retention-days: 5
